export const mockJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    company_logo: "/placeholder.svg?height=64&width=64&text=TC",
    description:
      "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for developing user-facing web applications using modern JavaScript frameworks. The ideal candidate should have strong experience with React, TypeScript, and modern CSS frameworks.",
    location: "San Francisco, CA",
    salary: "$120,000 - $160,000",
    type: "Full-time",
    remote: true,
    experience: "Senior",
    skills: ["React", "TypeScript", "JavaScript", "CSS", "HTML", "Node.js"],
    requirements: [
      "5+ years of frontend development experience",
      "Expert knowledge of React and TypeScript",
      "Experience with modern CSS frameworks (Tailwind, Styled Components)",
      "Strong understanding of web performance optimization",
      "Experience with testing frameworks (Jest, Cypress)",
      "Bachelor's degree in Computer Science or equivalent experience",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Health, dental, and vision insurance",
      "Flexible work arrangements",
      "Professional development budget",
      "Unlimited PTO",
      "401(k) matching",
    ],
    status: "active" as const,
    posted_date: "2024-01-15T10:00:00Z",
    employer_id: "emp-1",
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    company_logo: "/placeholder.svg?height=64&width=64&text=SX",
    description:
      "Join our fast-growing startup as a Full Stack Engineer. You'll work on both frontend and backend systems, building scalable web applications that serve millions of users. We're looking for someone who thrives in a fast-paced environment and loves solving complex problems.",
    location: "New York, NY",
    salary: "$100,000 - $140,000",
    type: "Full-time",
    remote: false,
    experience: "Mid-level",
    skills: ["JavaScript", "Python", "React", "Django", "PostgreSQL", "AWS"],
    requirements: [
      "3+ years of full-stack development experience",
      "Proficiency in JavaScript and Python",
      "Experience with React and Django/Flask",
      "Knowledge of database design and SQL",
      "Familiarity with cloud platforms (AWS, GCP, or Azure)",
      "Strong problem-solving and communication skills",
    ],
    benefits: [
      "Competitive salary with equity upside",
      "Comprehensive health benefits",
      "Catered meals and snacks",
      "Learning and development opportunities",
      "Flexible vacation policy",
      "Modern office in downtown NYC",
    ],
    status: "active" as const,
    posted_date: "2024-01-14T14:30:00Z",
    employer_id: "emp-2",
  },
  {
    id: "3",
    title: "DevOps Engineer",
    company: "CloudTech Solutions",
    company_logo: "/placeholder.svg?height=64&width=64&text=CT",
    description:
      "We're seeking a DevOps Engineer to help us scale our infrastructure and improve our deployment processes. You'll work with cutting-edge cloud technologies and help build robust, scalable systems that power our applications.",
    location: "Austin, TX",
    salary: "$110,000 - $150,000",
    type: "Full-time",
    remote: true,
    experience: "Mid-level",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Python", "Linux"],
    requirements: [
      "3+ years of DevOps or infrastructure experience",
      "Strong experience with AWS services",
      "Proficiency with containerization (Docker, Kubernetes)",
      "Experience with Infrastructure as Code (Terraform, CloudFormation)",
      "Knowledge of CI/CD pipelines and automation",
      "Strong scripting skills (Python, Bash)",
    ],
    benefits: [
      "Competitive salary and bonus structure",
      "Full health, dental, and vision coverage",
      "Remote work flexibility",
      "Professional certification reimbursement",
      "Generous PTO policy",
      "Home office setup allowance",
    ],
    status: "active" as const,
    posted_date: "2024-01-13T09:15:00Z",
    employer_id: "emp-3",
  },
  {
    id: "4",
    title: "Product Manager",
    company: "InnovateLabs",
    company_logo: "/placeholder.svg?height=64&width=64&text=IL",
    description:
      "Lead product strategy and execution for our flagship SaaS platform. You'll work closely with engineering, design, and sales teams to deliver features that delight our customers and drive business growth.",
    location: "Seattle, WA",
    salary: "$130,000 - $170,000",
    type: "Full-time",
    remote: false,
    experience: "Senior",
    skills: ["Product Management", "Analytics", "SQL", "Agile", "User Research", "Strategy"],
    requirements: [
      "5+ years of product management experience",
      "Experience with B2B SaaS products",
      "Strong analytical and data-driven decision making",
      "Excellent communication and leadership skills",
      "Experience with Agile development methodologies",
      "MBA or equivalent experience preferred",
    ],
    benefits: [
      "Competitive salary with performance bonuses",
      "Equity participation",
      "Premium health benefits",
      "Flexible work schedule",
      "Professional development budget",
      "Team building and company events",
    ],
    status: "active" as const,
    posted_date: "2024-01-12T16:45:00Z",
    employer_id: "emp-4",
  },
  {
    id: "5",
    title: "UX/UI Designer",
    company: "DesignStudio Pro",
    company_logo: "/placeholder.svg?height=64&width=64&text=DS",
    description:
      "Create beautiful, intuitive user experiences for our digital products. You'll be responsible for the entire design process from user research to final implementation, working closely with product and engineering teams.",
    location: "Los Angeles, CA",
    salary: "$90,000 - $120,000",
    type: "Full-time",
    remote: true,
    experience: "Mid-level",
    skills: ["Figma", "Sketch", "Adobe Creative Suite", "Prototyping", "User Research", "HTML/CSS"],
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)",
      "Strong portfolio demonstrating design process and outcomes",
      "Experience with user research and usability testing",
      "Understanding of front-end development principles",
      "Excellent visual design and typography skills",
    ],
    benefits: [
      "Competitive salary",
      "Health and wellness benefits",
      "Remote work options",
      "Creative software licenses",
      "Conference and workshop attendance",
      "Collaborative and creative work environment",
    ],
    status: "active" as const,
    posted_date: "2024-01-11T11:20:00Z",
    employer_id: "emp-5",
  },
]

export const mockUsers = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    role: "job_seeker" as const,
    profile_data: {
      skills: ["JavaScript", "React", "Node.js"],
      experience: "Mid-level",
      location: "San Francisco, CA",
    },
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@techcorp.com",
    role: "employer" as const,
    profile_data: {
      company: "TechCorp Inc.",
      position: "HR Manager",
    },
    created_at: "2024-01-02T00:00:00Z",
  },
]

export const mockApplications = [
  {
    id: "app-1",
    job_id: "1",
    user_id: "user-1",
    status: "pending" as const,
    applied_at: "2024-01-15T12:00:00Z",
  },
]
